import { motion, AnimatePresence } from 'framer-motion';
import { useState, useRef } from 'react';
import { Download, Printer, X, FileText, Award, Target, AlertTriangle } from 'lucide-react';

export default function PaperViewer({ paper, isOpen, onClose, language = 'en' }) {
  const [expandedSections, setExpandedSections] = useState({});
  const printRef = useRef();

  if (!isOpen || !paper) return null;

  const toggleSection = (sectionId) => {
    setExpandedSections(prev => ({
      ...prev,
      [sectionId]: !prev[sectionId]
    }));
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const printContent = document.getElementById('print-area');
    const printWindow = window.open('', '_blank');
    
    const subjectName = paper.subjectName || 'Subject';
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${subjectName} - CBSE 2027 Board Paper</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
              font-family: 'Times New Roman', Times, serif; 
              padding: 30px; 
              line-height: 1.8; 
              font-size: 12pt;
              max-width: 800px;
              margin: 0 auto;
            }
            .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 15px; }
            .header h1 { font-size: 18pt; margin-bottom: 8px; }
            .header p { font-size: 11pt; margin-bottom: 4px; }
            .subject-title { font-size: 16pt; font-weight: bold; margin: 15px 0; text-align: center; }
            .instructions { font-size: 10pt; margin-bottom: 15px; padding: 10px; border: 1px solid #333; }
            .section { margin-bottom: 25px; }
            .section-title { font-size: 12pt; font-weight: bold; margin-bottom: 10px; border-bottom: 1px solid #666; padding-bottom: 5px; }
            .question { margin-bottom: 12px; page-break-inside: avoid; }
            .q-number { font-weight: bold; }
            .q-text { margin-left: 5px; }
            .marks { float: right; font-weight: bold; }
            .options { margin-left: 25px; margin-top: 5px; }
            .option { margin-bottom: 3px; }
            .sub-questions { margin-left: 20px; margin-top: 8px; }
            .sub-q { margin-bottom: 5px; }
            .case-study { background: #f5f5f5; padding: 10px; margin: 10px 0; border-left: 3px solid #333; }
            .case-context { font-style: italic; margin-bottom: 8px; }
            .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #333; font-size: 9pt; text-align: center; }
            @media print {
              body { padding: 0; }
              .question { page-break-inside: avoid; }
            }
          </style>
        </head>
        <body>
          ${printContent.innerHTML}
          <div class="footer">
            <p>Generated by CBSE 2027 Intelligence Engine | Confidence: ${paper.confidenceScore}%</p>
            <p>AI Examiner Strategy: ${paper.config?.aiPowered ? 'AI-Powered Prediction' : 'Algorithm-Based'}</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  const sectionA = paper.questions.filter(q => q.type === 'mcq' || q.marks === 1);
  const sectionB = paper.questions.filter(q => q.type === 'short_answer' || q.marks === 2);
  const sectionC = paper.questions.filter(q => q.type === 'long_answer' || q.marks >= 3);

  const labels = {
    sectionA: language === 'hi' ? 'खंड अ - बहुविकल्पी प्रश्न (1 अंक प्रत्येक)' : 'Section A - Multiple Choice Questions (1 mark each)',
    sectionB: language === 'hi' ? 'खंड ब - लघु उत्तरीय प्रश्न (2 अंक प्रत्येक)' : 'Section B - Short Answer Questions (2 marks each)',
    sectionC: language === 'hi' ? 'खंड स - दीर्घ उत्तरीय प्रश्न (3-5 अंक)' : 'Section C - Long Answer Questions (3-5 marks)',
    instructions: language === 'hi' 
      ? 'निर्देश: सभी प्रश्न अनिवार्य हैं। प्रत्येक प्रश्न के लिए उचित उत्तर चुनें।'
      : 'Instructions: All questions are compulsory. Choose the correct answer for each question.',
    question: language === 'hi' ? 'प्रश्न' : 'Q',
    marks: language === 'hi' ? 'अंक' : 'marks',
    caseStudy: language === 'hi' ? 'केस स्टडी' : 'Case Study',
    hots: language === 'hi' ? 'उच्च-स्तरीय चिंतन कौशल' : 'HOTS',
    examinerNote: language === 'hi' ? 'परीक्षक नोट' : 'Examiner Note',
    downloadPdf: language === 'hi' ? 'PDF डाउनलोड करें' : 'Download PDF',
    print: language === 'hi' ? 'प्रिंट करें' : 'Print',
    close: language === 'hi' ? 'बंद करें' : 'Close',
    confidence: language === 'hi' ? 'विश्वास स्कोर' : 'Confidence Score',
    aiPowered: language === 'hi' ? 'AI द्वारा निर्मित' : 'AI Generated',
  };

  const renderQuestion = (q, index, section) => {
    const qNum = section === 'A' ? index + 1 : 
                 section === 'B' ? index + 1 : 
                 index + 1;
    
    return (
      <div key={q.id || `q-${index}`} className="mb-4 p-3 bg-slate-800/30 rounded-lg">
        <div className="flex justify-between items-start mb-2">
          <div className="flex items-center gap-2">
            <span className="text-emerald-400 font-bold font-mono">
              {section}{qNum}.
            </span>
            {q.difficulty === 'hard' && (
              <span className="px-2 py-0.5 bg-red-500/20 text-red-400 rounded text-xs flex items-center gap-1">
                <Target className="w-3 h-3" /> {labels.hots}
              </span>
            )}
            {q.caseStudy && (
              <span className="px-2 py-0.5 bg-blue-500/20 text-blue-400 rounded text-xs flex items-center gap-1">
                <FileText className="w-3 h-3" /> {labels.caseStudy}
              </span>
            )}
          </div>
          <span className="text-slate-500 text-sm font-mono">
            {q.marks} {labels.marks}
          </span>
        </div>
        
        <p className="text-slate-200 mb-2">{q.question}</p>
        
        {q.trap && (
          <div className="mt-2 p-2 bg-amber-500/10 border-l-2 border-amber-500 rounded text-xs text-amber-400">
            <span className="flex items-center gap-1">
              <AlertTriangle className="w-3 h-3" /> 
              {labels.examinerNote}: {q.trap}
            </span>
          </div>
        )}
        
        {q.options && q.options.length > 0 && (
          <div className="mt-3 space-y-1">
            {q.options.map((opt, i) => (
              <div key={i} className={`p-2 rounded text-sm ${
                q.correctAnswer === i 
                  ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30' 
                  : 'bg-slate-700/30 text-slate-400'
              }`}>
                <span className="font-mono mr-2">{String.fromCharCode(65 + i)}.</span>
                {opt}
              </div>
            ))}
          </div>
        )}

        {q.hasDiagram && q.diagramDescription && (
          <div className="mt-4 p-4 bg-[#0B0C10]/40 border border-[#66FCF1]/20 rounded-xl flex flex-col items-center justify-center text-center">
            <div className="p-3 bg-[#66FCF1]/10 rounded-full mb-3 shadow-[0_0_15px_rgba(102,252,241,0.2)]">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#66FCF1" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M3 3v18h18" />
                <path d="M18 17V9" />
                <path d="M13 17V5" />
                <path d="M8 17v-3" />
              </svg>
            </div>
            <p className="text-xs text-[#66FCF1] font-bold uppercase tracking-wider mb-1">Attached Diagram Context</p>
            <p className="text-sm text-slate-300">{q.diagramDescription}</p>
          </div>
        )}
        
        {q.caseStudy && (
          <div className="mt-3 p-3 bg-blue-500/10 border-l-2 border-blue-500 rounded">
            <p className="text-sm text-blue-300 mb-2">{q.caseStudy.context || q.caseStudy.scenario}</p>
            {q.caseStudy.questions && (
              <div className="ml-4 space-y-1">
                {q.caseStudy.questions.map((sq, si) => (
                  <p key={si} className="text-sm text-slate-300">({si + 1}) {sq}</p>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    );
  };

  return (
    <AnimatePresence>
        <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-[#0B0C10]/95 backdrop-blur-xl z-40 overflow-y-auto"
      >
        <div className="min-h-screen py-8 px-4">
          <div className="max-w-4xl mx-auto">
            {/* Header Controls */}
            <div className="flex items-center justify-between mb-6 no-print sticky top-4 z-10">
              <button
                onClick={onClose}
                className="p-2 bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
              <div className="flex items-center gap-3">
                <div className="px-3 py-1 bg-emerald-500/20 text-emerald-400 rounded-full text-sm flex items-center gap-2">
                  <Award className="w-4 h-4" />
                  {paper.confidenceScore}% {labels.confidence}
                </div>
                {paper.config?.aiPowered && (
                  <span className="px-3 py-1 bg-purple-500/20 text-purple-400 rounded-full text-xs">
                    {labels.aiPowered}
                  </span>
                )}
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-800 rounded-lg text-slate-300 hover:text-white transition-colors"
                >
                  <Printer className="w-4 h-4" />
                  {labels.print}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-4 py-2 bg-emerald-500 rounded-lg text-white hover:bg-emerald-600 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  {labels.downloadPdf}
                </button>
              </div>
            </div>

            {/* Paper Content */}
            <div id="print-area" className="print-paper bg-white text-black rounded-xl p-8 shadow-2xl">
              {/* CBSE Header */}
              <div className="text-center border-b-2 border-black pb-4 mb-6">
                <h1 className="text-xl font-bold">CENTRAL BOARD OF SECONDARY EDUCATION</h1>
                <p className="text-base mt-1">भारतीय माध्यमिक शिक्षा बोर्ड</p>
                <p className="text-lg font-semibold mt-3">{paper.subjectName}</p>
                <p className="text-base mt-1">Class X | Session 2026-27</p>
                <p className="text-sm mt-1">Maximum Marks: 80 | Time: 3 Hours</p>
              </div>

              {/* Instructions */}
              <div className="mb-6 p-4 border border-gray-400 text-sm">
                <p className="font-semibold mb-2">General Instructions:</p>
                <ul className="list-disc list-inside space-y-1">
                  <li>{labels.instructions}</li>
                  <li>Read each question carefully before answering.</li>
                  <li>For Section A: Choose the correct option and fill in the given space.</li>
                  <li>For Section B & C: Write your answer in the space provided.</li>
                </ul>
              </div>

              {/* Section A */}
              <div className="section mb-8">
                <h2 className="font-bold text-lg mb-4 border-b border-gray-400 pb-2">
                  {labels.sectionA}
                </h2>
                {sectionA.slice(0, 20).map((q, i) => renderQuestion(q, i, 'A'))}
              </div>

              {/* Section B */}
              <div className="section mb-8">
                <h2 className="font-bold text-lg mb-4 border-b border-gray-400 pb-2">
                  {labels.sectionB}
                </h2>
                {sectionB.slice(0, 15).map((q, i) => renderQuestion(q, i, 'B'))}
              </div>

              {/* Section C */}
              <div className="section mb-8">
                <h2 className="font-bold text-lg mb-4 border-b border-gray-400 pb-2">
                  {labels.sectionC}
                </h2>
                {sectionC.slice(0, 8).map((q, i) => renderQuestion(q, i, 'C'))}
              </div>

              {/* Footer */}
              <div className="mt-8 pt-4 border-t border-gray-400 text-sm text-gray-600">
                <p>Generated: {new Date(paper.generatedAt).toLocaleString()}</p>
                <p>Confidence: {paper.confidenceScore}% | Strategy: {paper.config?.aiPowered ? 'AI Examiner' : 'Algorithm'}</p>
                {paper.rawAI?.examinerStrategy && (
                  <div className="mt-2 p-2 bg-gray-100 rounded">
                    <p className="font-semibold">Examiner Strategy:</p>
                    <p className="text-xs">{paper.rawAI.examinerStrategy.reasoning || paper.rawAI.analysis?.reasoning}</p>
                  </div>
                )}
              </div>
            </div>

            {/* Analysis Section (Screen Only) */}
            {paper.rawAI?.examinerStrategy && (
              <div className="mt-6 p-4 bg-slate-800/50 rounded-xl no-print">
                <h3 className="text-sm font-semibold text-slate-300 mb-3 flex items-center gap-2">
                  <Brain className="w-4 h-4 text-emerald-400" />
                  {language === 'hi' ? 'परीक्षक रणनीति' : 'Examiner Strategy'}
                </h3>
                <div className="space-y-2 text-sm">
                  {paper.rawAI.examinerStrategy.dormantTopicsUsed && (
                    <p className="text-slate-400">
                      <span className="text-amber-400">🔄 Dormant Topics:</span> {paper.rawAI.examinerStrategy.dormantTopicsUsed.join(', ')}
                    </p>
                  )}
                  {paper.rawAI.examinerStrategy.evergreenTopicsUsed && (
                    <p className="text-slate-400">
                      <span className="text-emerald-400">✅ Evergreen Topics:</span> {paper.rawAI.examinerStrategy.evergreenTopicsUsed.join(', ')}
                    </p>
                  )}
                  {paper.rawAI.examinerStrategy.caseStudyTopics && (
                    <p className="text-slate-400">
                      <span className="text-blue-400">📊 Case Studies:</span> {paper.rawAI.examinerStrategy.caseStudyTopics.join(', ')}
                    </p>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}

function Brain({ className }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M12 2a7 7 0 0 0-7 7c0 2.38 1.19 4.47 3 5.74V17a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-2.26c1.81-1.27 3-3.36 3-5.74a7 7 0 0 0-7-7z"/>
      <path d="M9 21h6"/>
      <path d="M12 17v4"/>
    </svg>
  );
}